### ISSUE TITLE
AttributeError: 'Network' object has no attribute 'patk'

### ISSUE THREAD

**Issue by Yong-DAI** [dhruvramani/C2AE-Multilabel-Classification#2]
=> Training Model
Traceback (most recent call last):

  File "<ipython-input-1-dabc36652bbf>", line 1, in <module>
    runfile('/home/dy/dy-doc/C2AE-Multilabel-Classification-master/model/src/__main__.py', wdir='/home/dy/dy-doc/C2AE-Multilabel-Classification-master/model/src')

  File "/home/dy/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "/home/dy/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/dy/dy-doc/C2AE-Multilabel-Classification-master/model/src/__main__.py", line 204, in <module>
    main() # Phew!

  File "/home/dy/dy-doc/C2AE-Multilabel-Classification-master/model/src/__main__.py", line 189, in main
    loss_dict = train_model(config)

  File "/home/dy/dy-doc/C2AE-Multilabel-Classification-master/model/src/__main__.py", line 180, in train_model
    model, sess = init_model(config)

  File "/home/dy/dy-doc/C2AE-Multilabel-Classification-master/model/src/__main__.py", line 163, in init_model
    model = Model(config)

  File "/home/dy/dy-doc/C2AE-Multilabel-Classification-master/model/src/__main__.py", line 26, in __init__
    self.patk = self.net.patk(self.y, self.y_pred)

AttributeError: 'Network' object has no attribute 'patk'

it's true that i didn't fint patk function in network.py, do you know how to fix this?

**Comment by dhruvramani** [comment]
Hey I just checked. That line was useless, and was there because previously I had been using a tensorflow based patk function. I have defined the patk in eval_performance.py and have been using that in rest of the code.

**Comment by Yong-DAI** [comment]
thanks a lot. so ,when I edit that line to self.patk=patk(self.y,self.y_pred),this mean that I delete "self.net", but when I run this again ,I got another error, in eval_performance.py, line11,it said typeerror,__index__ returned non-int(type nonetype)

**Comment by Yong-DAI** [comment]
o ,I just comment that line ,now ,it works,thank u，thank u very much

**Comment by dhruvramani** [comment]
No problem! :)

**Comment by Yong-DAI** [comment]
ha, when I read the lines in networks.py, I saw the line" #my blood ,my sweat and my tears were also embedded into the embedding", I'm touched , I just want to thank u, thank u for your coding work ,and thank u for your sharing!

**Comment by dhruvramani** [comment]
Haha, this made my day! Thank you for appreciating.
Also, try avoiding usage of loops with TensorFlow, it's a pain.
Have a nice day :)

**Comment by Yong-DAI** [comment]
Hi, I'm a little confused, one thing，could you please tell me about the run.py, because I don't find any other py files that use this run.py,  "run" in the "sess.run" in other py files should be a default function included in the tf.session of tensorflow, not this run.py ,right?

**Comment by dhruvramani** [comment]
Ya, no file is using run.py. And yes, `sess.run` is from TensorFlow. It's actually an incomplete file, you could run the code through __main__.py or run.py (with some differences). You can try running it through run.py but I can't guarantee that it will work.
